// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7qRRg273qk8jgxQOWbepnW1laONUPoU',
    appId: '1:38090365169:web:7b04b46c410e822b8f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    authDomain: 'servicesphere-2a2f1.firebaseapp.com',
    databaseURL: 'https://servicesphere-2a2f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    measurementId: 'G-78BH1BDBVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKConASxVx5hZExMlrO9-iYEdha3AFkTY',
    appId: '1:38090365169:android:70f69d2e76ba5a7c8f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    databaseURL: 'https://servicesphere-2a2f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczGK-SZoLhaUs0I3RikmWuXXCP_vSTHY',
    appId: '1:38090365169:ios:bb0e4a6c8906f4c48f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    databaseURL: 'https://servicesphere-2a2f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    androidClientId: '38090365169-1ldubpk7969omle3i7ls111aurjatf8j.apps.googleusercontent.com',
    iosClientId: '38090365169-hcsln1j9leem01b87ivloaapgbhh1num.apps.googleusercontent.com',
    iosBundleId: 'com.servicesphere.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7qRRg273qk8jgxQOWbepnW1laONUPoU',
    appId: '1:38090365169:web:678df1469abc49128f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    authDomain: 'servicesphere-2a2f1.firebaseapp.com',
    databaseURL: 'https://servicesphere-2a2f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    measurementId: 'G-088QNH5Q86',
  );

}