// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7qRRg273qk8jgxQOWbepnW1laONUPoU',
    appId: '1:38090365169:web:3f429c2d1a955a8c8f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    authDomain: 'servicesphere-2a2f1.firebaseapp.com',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    measurementId: 'G-QZ504YY5H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKConASxVx5hZExMlrO9-iYEdha3AFkTY',
    appId: '1:38090365169:android:38ae2b35e39f892d8f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczGK-SZoLhaUs0I3RikmWuXXCP_vSTHY',
    appId: '1:38090365169:ios:905cd74281a04e9c8f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    iosBundleId: 'com.example.servicesphereagent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF7qRRg273qk8jgxQOWbepnW1laONUPoU',
    appId: '1:38090365169:web:78b35148338897088f7150',
    messagingSenderId: '38090365169',
    projectId: 'servicesphere-2a2f1',
    authDomain: 'servicesphere-2a2f1.firebaseapp.com',
    storageBucket: 'servicesphere-2a2f1.firebasestorage.app',
    measurementId: 'G-8Z2BPV0Q67',
  );
}
